### PR TITLE
➕  Add storybook

### PR DESCRIPTION
**Pull request by oersoy91**
- Install storybook with: `npx sb init`

- Remove example stories folder

- Created `components` folder with example Button component

- Set stories folder in `.storybook/main.js`

- Load example component in `pages/index.tsx`

- Ignore `/storybook-static`

- Add `.eslintignore`

https://storybook.js.org/docs/react/get-started/install

### CODE REVIEW

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by fgottesmann — APPROVED** [review]
lgtm :)

**Review by fre-ben — APPROVED** [review]
LGTM 🤖

**Review by mrana17 — APPROVED** [review]
gj 🚀

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Pull request merged**
